### RNN from scratch

---
Article: [Building RNNs is Fun with PyTorch and Google Colab](https://medium.com/dair-ai/building-rnns-is-fun-with-pytorch-and-google-colab-3903ea9a3a79)

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import numpy as np

We will build the following architecture.

<img src="https://miro.medium.com/max/969/1*o65pRKyHxhw7m8LgMbVERg.png" alt="NN_Architecture" style="width: 500px;"/>
<center>Image from: <a href="https://medium.com/dair-ai/building-rnns-is-fun-with-pytorch-and-google-colab-3903ea9a3a79">Building RNNs is Fun with PyTorch and Google Colab (Aug 19, 2018)</a></center>

In [2]:
class RNN(nn.Module):
    def __init__(self, n_inputs, n_neurons):
        super(RNN, self).__init__()
        
        self.wx = torch.randn(n_inputs, n_neurons)
        self.wy = torch.randn(n_neurons, n_neurons)
        
        self.b = torch.zeros(1, n_neurons)
        
    def forward(self, x0, x1):
        self.y0 = torch.tanh(torch.mm(x0, self.wx) + self.b)
        self.y1 = torch.tanh(torch.mm(self.y0, self.wy) + torch.mm(x1, self.wx) + self.b)
        return self.y0, self.y1

#### Single neuron

In [3]:
N_INPUT = 4
N_NEURONS = 1

In [4]:
x0 = torch.tensor([[0, 1, 2, 0],
                  [3, 4, 5, 0],
                  [6, 7, 8, 0],
                  [9, 0, 1, 0]], dtype=torch.float)
x1 = torch.tensor([[9, 8, 7, 0],
                  [0, 0, 0, 0],
                  [6, 5, 4, 0],
                  [3, 2, 1, 0]], dtype=torch.float)

In [5]:
model = RNN(N_INPUT, N_NEURONS)

In [6]:
y0, y1 = model(x0, x1)

In [7]:
print('{}\n{}'.format(y0, y1))

tensor([[0.4530],
        [1.0000],
        [1.0000],
        [1.0000]])
tensor([[ 1.0000],
        [-0.9544],
        [ 1.0000],
        [ 1.0000]])


#### Multiple neurons

In [8]:
N_INPUT = 3
N_NEURONS = 5

In [9]:
x0 = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8],
                  [9, 0, 1]], dtype=torch.float)
x1 = torch.tensor([[9, 8, 7],
                  [0, 0, 0],
                  [6, 5, 4],
                  [3, 2, 1]], dtype=torch.float)

In [10]:
model = RNN(N_INPUT, N_NEURONS)

In [11]:
y0, y1 = model(x0, x1)

In [12]:
print('{}\n{}'.format(y0 ,y1))

tensor([[-0.8887,  0.8353,  0.8815, -0.7926,  0.9857],
        [-0.9994,  0.9995,  1.0000, -0.9877,  1.0000],
        [-1.0000,  1.0000,  1.0000, -0.9993,  1.0000],
        [ 0.6267,  1.0000,  1.0000, -0.9159,  0.9984]])
tensor([[-1.0000,  1.0000,  1.0000, -1.0000,  1.0000],
        [-0.5925,  0.3841,  0.9867, -0.9946, -0.3306],
        [-0.9998,  0.9999,  1.0000, -0.9999,  1.0000],
        [-0.9982,  0.9997,  1.0000, -0.2359,  1.0000]])
